### ISSUE TITLE
zip file does not belong in a source code repository

### ISSUE THREAD

**Issue by strk** [JanekWMJ/J-Rectifier#2]
What is https://github.com/JanekWMJ/J-Rectifier/blob/master/J_Rectifier1.0.zip for ?
Maybe you want to remove that (just tag 1.0 to have GitHub provide a download URL from the Releases tab)

**Comment by JanekWMJ** [comment]
Thet's the zipped plugin... but i think your idea is better.
But i wonder if it will not change a path....

2017-03-21 16:24 GMT+01:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
What do you mean by "change a path" ?

**Comment by JanekWMJ** [comment]
Sorry, I ment, change URL rather than path.
I thinked if that kind of action won't change the url of repository, but it
is only the catalog within repository, so it's ok. :-)
Thanks for a good piece of advice by the way!

2017-03-21 16:40 GMT+01:00 Sandro Santilli <notifications@github.com>:
